### ISSUE TITLE
pip install tr - not documented that 'tr' requires module 'numpy', 

### ISSUE THREAD

**Issue by artejera** [ikegami-yukino/python-tr#5]
Greetings !

I just want to report that installing 'pip3.8 install tr' in my case failed because it found and 'import numpy',  tried then to install 'numpy' and somewhere in a compilationn it fails.

I merely suggest that the 'numpy' dependency be documented, right ?
Best regards
Ariel

**Comment by ikegami-yukino** [comment]
This repository is not `tr` in PyPI, but `python-tr`.

The `python-tr` doesn't use `numpy`.
https://github.com/ikegami-yukino/python-tr/search?q=import+numpy
